# Generated by Django 5.2.6 on 2025-12-02 01:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial_proposal', '0001_initial'),
        ('nmacost', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('director_full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО руководителя')),
                ('director_position', models.CharField(blank=True, max_length=255, verbose_name='Должность руководителя')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/', verbose_name='Логотип предприятия')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='Контактный телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки организации',
                'verbose_name_plural': 'Настройки организации',
            },
        ),
        migrations.CreateModel(
            name='CostCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Заказчик')),
                ('project_brief', models.TextField(blank=True, verbose_name='Описание/ТЗ')),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Трудоемкость, ч')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ставка, ₽/ч')),
                ('infrastructure_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Инфраструктурные затраты')),
                ('other_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Прочие расходы')),
                ('management_overhead_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Управленческие расходы, %')),
                ('risk_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Риск, %')),
                ('profit_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('200.00'))], verbose_name='Маржа прибыли, %')),
                ('asset_capitalization_percent', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Доля капитализации НМА, %')),
                ('commercial_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('300.00'))], verbose_name='Наценка коммерческого предложения, %')),
                ('development_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Стоимость разработки проекта')),
                ('intangible_asset_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Стоимость нематериального актива')),
                ('commercial_offer_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Стоимость коммерческого предложения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_calculations', to='commercial_proposal.commercialproposal', verbose_name='Коммерческое предложение')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_calculations', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('nma_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_calculations', to='nmacost.nmacost', verbose_name='Стоимость НМА')),
            ],
            options={
                'verbose_name': 'Расчет стоимости',
                'verbose_name_plural': 'Расчеты стоимости',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('global_admin', 'Глобальный администратор'), ('commercial_director', 'Коммерческий директор'), ('accountant', 'Бухгалтер'), ('hr_specialist', 'Кадровик')], max_length=32)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_itcost_roles', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itcost_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Роль в системе расчета',
                'verbose_name_plural': 'Роли в системе расчета',
                'ordering': ('-assigned_at',),
                'unique_together': {('user', 'role')},
            },
        ),
    ]
