# Generated by Django 5.2.6 on 2025-09-21 13:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
        ('customers', '0001_initial'),
        ('employees', '0002_alter_employee_tax_rate'),
        ('equipment', '0001_initial'),
        ('subcontractors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('technical_spec', models.FileField(blank=True, null=True, upload_to='technical_specs/', verbose_name='Техническое задание')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Налоговая ставка (%)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итоговая стоимость')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Себестоимость')),
                ('cost_with_margin', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость с маржинальностью')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Чистая прибыль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ресурса')),
                ('resource_type', models.CharField(choices=[('employee', 'Сотрудник'), ('contractor', 'Исполнитель'), ('subcontractor', 'Субподрядчик'), ('equipment', 'Оборудование')], max_length=20, verbose_name='Тип ресурса')),
                ('service_name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество')),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Маржинальность (%)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Себестоимость')),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итоговая стоимость')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractors.contractor')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('subcontractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subcontractors.subcontractor')),
            ],
        ),
    ]
