# Generated by Django 5.2.6 on 2025-12-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_proposal', '0002_serviceitem_is_indefinite_serviceitem_monthly_cost_and_more'),
        ('contractors', '0001_initial'),
        ('employees', '0002_alter_employee_tax_rate'),
        ('equipment', '0001_initial'),
        ('nmacost', '0001_initial'),
        ('projects', '0001_initial'),
        ('subcontractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commercial_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial_proposal.commercialproposal', verbose_name='Коммерческое предложение'),
        ),
        migrations.AddField(
            model_name='project',
            name='nma_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nmacost.nmacost', verbose_name='Расчет НМА'),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractors.service', verbose_name='Услуга исполнителя'),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='subcontractor_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость за единицу (для субподрядчика)'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractors.contractor', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='subcontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subcontractors.subcontractor', verbose_name='Субподрядчик'),
        ),
    ]
