# Generated by Django 5.2.6 on 2025-12-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_proposal', '0003_commercialproposal_project'),
        ('customers', '0002_customer_can_be_shared_customer_project_and_more'),
        ('nmacost', '0002_remove_nmacost_project_name_nmacost_project'),
        ('projects', '0002_project_commercial_proposal_project_nma_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='commercial_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_projects', to='commercial_proposal.commercialproposal', verbose_name='Коммерческое предложение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_projects', to='customers.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nma_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_projects', to='nmacost.nmacost', verbose_name='Расчет НМА'),
        ),
    ]
