# Generated by Django 5.2.6 on 2026-01-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_commercial_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общая стоимость'),
        ),
    ]
