# Generated by Django 5.2.6 on 2026-01-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итоговая стоимость'),
        ),
    ]
