# Generated by Django 5.2.6 on 2025-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tax_rate',
            field=models.CharField(choices=[('30.2', '30.2% (стандартная)'), ('7.6', '7.6% (льготная)')], default='30.2', max_length=10, verbose_name='Налоговая ставка (%)'),
        ),
    ]
