# Generated by Django 5.2.6 on 2025-12-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmacost', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nmacost',
            name='project_name',
        ),
        migrations.AddField(
            model_name='nmacost',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nma_costs', to='workspace.project', verbose_name='Проект'),
        ),
    ]
