# Generated by Django 5.2.6 on 2026-01-06 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmacost', '0003_alter_nmacost_project'),
        ('workspace', '0002_project_commercial_proposal_project_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmacost',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nma_cost_entries', to='workspace.project', verbose_name='Проект'),
        ),
    ]
