# Generated by Django 5.2.6 on 2025-09-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('acquisition_type', models.CharField(choices=[('own', 'Собственное'), ('rent', 'В аренде')], max_length=10, verbose_name='Тип приобретения')),
                ('operational_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Эксплуатационная стоимость')),
                ('unit', models.CharField(choices=[('hours', 'Часы'), ('days', 'Дни'), ('full', 'Полная стоимость')], max_length=10, verbose_name='Единица измерения')),
                ('service_cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость услуг за единицу измерения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
            },
        ),
    ]
