# Generated by Django 5.2.6 on 2025-12-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='can_be_shared',
            field=models.BooleanField(default=False, verbose_name='Можно использовать в других проектах'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='workspace.project', verbose_name='Проект'),
        ),
    ]
