# Generated by Django 5.2.6 on 2025-09-20 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('contractor_type', models.CharField(choices=[('legal', 'Юридическое лицо'), ('individual', 'Индивидуальный предприниматель')], max_length=20, verbose_name='Тип контрагента')),
                ('inn', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10,12}$', 'ИНН должен содержать 10 или 12 цифр')], verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'КПП должен содержать 9 цифр')], verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{13,15}$', 'ОГРН должен содержать 13 или 15 цифр')], verbose_name='ОГРН/ОГРНИП')),
                ('legal_address', models.TextField(verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(verbose_name='Фактический адрес')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{0,19}$', 'Введите корректный номер телефона')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('director_name', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Наименование банка')),
                ('bank_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('corr_account', models.CharField(max_length=20, verbose_name='Корреспондентский счет')),
                ('bik', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'БИК должен содержать 9 цифр')], verbose_name='БИК')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Субподрядчик',
                'verbose_name_plural': 'Субподрядчики',
                'ordering': ['name'],
            },
        ),
    ]
