# Generated by Django 5.2.6 on 2025-12-09 15:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontractors', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractor',
            name='can_be_shared',
            field=models.BooleanField(default=False, verbose_name='Можно использовать в других проектах'),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractors', to='workspace.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='inn',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10,12}$', 'ИНН должен содержать 10 или 12 цифр')], verbose_name='ИНН'),
        ),
        migrations.AlterUniqueTogether(
            name='subcontractor',
            unique_together={('project', 'inn')},
        ),
    ]
