# Generated by Django 5.2.6 on 2025-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('customer_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('entrepreneur', 'Индивидуальный предприниматель'), ('legal', 'Юридическое лицо')], max_length=20, verbose_name='Тип Заказчика')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Контактный e-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактный номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['-created_at'],
            },
        ),
    ]
