# Generated by Django 5.2.6 on 2025-12-09 15:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_proposal', '0003_commercialproposal_project'),
        ('contractors', '0002_contractor_can_be_shared_contractor_project'),
        ('customers', '0002_customer_can_be_shared_customer_project_and_more'),
        ('employees', '0003_employee_can_be_shared_employee_project'),
        ('equipment', '0002_equipment_can_be_shared_equipment_project'),
        ('nmacost', '0002_remove_nmacost_project_name_nmacost_project'),
        ('subcontractors', '0002_subcontractor_can_be_shared_subcontractor_project_and_more'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commercial_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_projects', to='commercial_proposal.commercialproposal', verbose_name='Коммерческое предложение'),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Себестоимость'),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_with_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость с маржинальностью'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspace_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_projects', to='customers.customer', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='project',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Чистая прибыль'),
        ),
        migrations.AddField(
            model_name='project',
            name='nma_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_projects', to='nmacost.nmacost', verbose_name='Расчет НМА'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='project',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Налоговая ставка (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_spec',
            field=models.FileField(blank=True, null=True, upload_to='technical_specs/', verbose_name='Техническое задание'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итоговая стоимость'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Администратор рабочей области'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='subdomain',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Поддомен может содержать только буквы, цифры, дефисы и подчеркивания', regex='^[a-zA-Z0-9_-]+$')], verbose_name='Поддомен'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ресурса')),
                ('resource_type', models.CharField(choices=[('employee', 'Сотрудник'), ('contractor', 'Исполнитель'), ('subcontractor', 'Субподрядчик'), ('equipment', 'Оборудование')], max_length=20, verbose_name='Тип ресурса')),
                ('service_name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество')),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Маржинальность (%)')),
                ('subcontractor_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость за единицу (для субподрядчика)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Себестоимость')),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итоговая стоимость')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_project_resources', to='contractors.contractor', verbose_name='Исполнитель')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_project_resources', to='employees.employee', verbose_name='Сотрудник')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_project_resources', to='equipment.equipment', verbose_name='Оборудование')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectresource_set', to='workspace.project')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_project_resources', to='contractors.service', verbose_name='Услуга исполнителя')),
                ('subcontractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_project_resources', to='subcontractors.subcontractor', verbose_name='Субподрядчик')),
            ],
        ),
    ]
