# Generated by Django 5.2.6 on 2025-09-21 13:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рабочей области')),
                ('subdomain', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Поддомен может содержать только буквы, цифры, дефисы и подчеркивания', regex='^[a-zA-Z0-9_-]+$')], verbose_name='Поддомен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_control_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Администратор рабочей области')),
            ],
            options={
                'verbose_name': 'Рабочая область Control',
                'verbose_name_plural': 'Рабочие области Control',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование проектов'), ('admin', 'Администратор')], default='view', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_members', to='workspace_control.workspace')),
            ],
            options={
                'verbose_name': 'Участник рабочей области',
                'verbose_name_plural': 'Участники рабочих областей',
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
