# Generated by Django 5.2.6 on 2025-09-19 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('contract_type', models.CharField(choices=[('GPH', 'ГПХ'), ('NPD', 'НПД')], max_length=3, verbose_name='Тип оформления')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Налоговая ставка (%)')),
                ('default_unit', models.CharField(blank=True, choices=[('hours', 'Часы'), ('days', 'Дни'), ('fixed', 'Полная стоимость')], max_length=10, null=True, verbose_name='Единица измерения')),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость за единицу')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование услуги')),
                ('unit', models.CharField(choices=[('hours', 'Часы'), ('days', 'Дни'), ('fixed', 'Полная стоимость')], max_length=10, verbose_name='Единица измерения')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за единицу')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='contractors.contractor', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Услуга исполнителя',
                'verbose_name_plural': 'Услуги исполнителей',
            },
        ),
    ]
