# Generated by Django 5.2.6 on 2025-09-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата формирования')),
                ('technical_spec', models.TextField(verbose_name='Техническое задание')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая стоимость')),
                ('manager_position', models.CharField(max_length=100, verbose_name='Должность руководителя')),
                ('manager_name', models.CharField(max_length=100, verbose_name='ФИО руководителя')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='Email руководителя')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Количество часов')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='commercial_proposal.commercialproposal')),
            ],
            options={
                'verbose_name': 'Позиция услуги',
                'verbose_name_plural': 'Позиции услуг',
            },
        ),
    ]
