# Generated by Django 5.2.6 on 2025-12-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='is_indefinite',
            field=models.BooleanField(default=False, verbose_name='Бессрочный срок'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='monthly_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма в месяц'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
