# Generated by Django 5.2.6 on 2025-12-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_proposal', '0002_serviceitem_is_indefinite_serviceitem_monthly_cost_and_more'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproposal',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to='workspace.project', verbose_name='Проект'),
        ),
    ]
