# Generated by Django 5.2.6 on 2026-01-05 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_proposal', '0003_commercialproposal_project'),
        ('customers', '0002_customer_can_be_shared_customer_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialproposal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Заказчик'),
        ),
    ]
